name: Bug Report
description: Report an unexpected behavior.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Description
        Thanks for taking the time to create the Issue and welcome to the Noir community!
  - type: textarea
    id: aim
    attributes:
      label: Aim
      description: Describe what you tried to achieve.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Describe the bug. Supply error codes / terminal logs if applicable.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Describe the steps to reproduce the behavior.
      value: |
        1.
        2.
        3.
        4.
  - type: dropdown
    id: workaround
    attributes:
      label: Workaround
      description: Is there a workaround for this Issue? 
      options:
        - "Yes"
  - type: textarea
    id: workaround_description
    attributes:
      label: Workaround Description
      description: If yes, supplement how could the Issue be worked around.
  - type: dropdown
    id: impact
    attributes:
      label: Project Impact
      description: How does this affect a project you or others are working on? 
      options:
        - "Nice-to-have"
        - "Blocker"
  - type: input
    id: impact_context
    attributes:
      label: Impact Context
      description: If a nice-to-have / blocker, supplement how does this Issue affect the project.
  - type: input
    id: additional
    attributes:
      label: Additional Context
      description: Supplement further information if applicable.
  - type: markdown
    attributes:
      value: |
        # Environment
        Specify your version of Noir and Proving Backend tooling used.
  - type: input
    id: nargo-version
    attributes:
      label: Nargo Version
      description: Output of running `nargo --version`
      placeholder: "nargo version = 0.32.0 noirc version = 0.32.0+c679f01a19b02ad2ac2287c8e699b46887f7872c (git version hash: c679f01a19b02ad2ac2287c8e699b46887f7872c, is dirty: false)"
  - type: input
    id: noirjs-version
    attributes:
      label: NoirJS Version
      description: Version number of `noir_js` in `package.json`
      placeholder: "0.32.0"
  - type: input
    id: backend-version
    attributes:
      label: Proving Backend Tooling & Version
      description: Type of tooling and version of the Proving Backend used
      placeholder: "Barretenberg CLI bb 0.46.1"
  - type: markdown
    attributes:
      value: |
        # Pull Request
  - type: dropdown
    id: pr_preference
    attributes:
      label: Would you like to submit a PR for this Issue?
      description: Fellow contributors are happy to provide support where applicable.
      options:
        - "Maybe"
        - "Yes"
  - type: input
    id: pr_support
    attributes:
      label: Support Needs
      description: Support from other contributors you are looking for to create a PR for this Issue.
