name: Rust Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      toolchain:
        required: true
        type: string
      working-directory:
        default: "."
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Install dependencies
        if: ${{ inputs.os == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt install libomp-dev

      - name: Install dependencies
        if: ${{ inputs.os == 'macos-latest' }}
        run: brew install llvm libomp cmake

      - name: Run cargo check
        working-directory: ${{ inputs.working-directory }}
        run: |
          cargo check --all-targets --verbose

      - name: Run cargo test
        working-directory: ${{ inputs.working-directory }}
        run: |
          cargo test -- --test-threads=1
